channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1588319295
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.12.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
