channels:
- currentCSV: eclipse-che-preview-kubernetes.v9.9.9-nightly.1590037976
  name: nightly
- currentCSV: eclipse-che-preview-kubernetes.v7.13.1
  name: stable
defaultChannel: stable
packageName: eclipse-che-preview-kubernetes
