apiVersion: v1
entries:
  eclipse-che:
  - annotations:
      artifacthub.io/crds: |-
        - kind: CheCluster
          version: v1
          name: checlusters.org.eclipse.che
          displayName: CheCluster
          description: The `CheCluster` custom resource allows defining and managing a Che server installation"
        - kind: CheBackupServerConfiguration
          version: v1
          name: chebackupserverconfigurations.org.eclipse.che
          displayName: CheBackupServerConfiguration
          description: The `CheBackupServerConfiguration` custom resource allows defining and managing Eclipse Che Backup Server Configurations
        - kind: CheClusterRestore
          version: v1
          name: checlusterrestores.org.eclipse.che
          displayName: CheClusterRestore
          description: The `CheClusterRestore` custom resource allows defining and managing Eclipse Che restore
        - kind: CheClusterBackup
          version: v1
          name: checlusterbackups.org.eclipse.che
          displayName: CheClusterBackup
          description: The `CheClusterBackup` custom resource allows defining and managing Eclipse Che backup
      artifacthub.io/crdsExamples: |
        - apiVersion: org.eclipse.che/v1
          kind: CheCluster
          metadata:
            name: eclipse-che
            namespace: eclipse-che
          spec:
            server:
              cheFlavor: ''
              cheClusterRoles: ''
              cheWorkspaceClusterRole: ''
              serverTrustStoreConfigMapName: ''
              gitSelfSignedCert: false
              tlsSupport: true
              proxyURL: ''
              proxyPort: ''
              proxyUser: ''
              proxyPassword: ''
              nonProxyHosts: ''
              workspaceNamespaceDefault: "<username>-che"
              allowUserDefinedWorkspaceNamespaces: false
              serverExposureStrategy: ''
            database:
              externalDb: false
              chePostgresHostName: ''
              chePostgresPort: ''
              chePostgresUser: ''
              chePostgresPassword: ''
              chePostgresDb: ''
            storage:
              pvcStrategy: 'common'
              pvcClaimSize: '10Gi'
              preCreateSubPaths: true
              postgresPVCStorageClassName: ''
              workspacePVCStorageClassName: ''
            auth:
              initialOpenShiftOAuthUser: true
              externalIdentityProvider: false
              identityProviderURL: ''
              identityProviderAdminUserName: ''
              identityProviderPassword: ''
              identityProviderRealm: ''
              identityProviderClientId: ''
              oAuthClientName: ''
              oAuthSecret: ''
            k8s:
              ingressDomain: '192.168.99.101.nip.io'
              ingressClass: ''
              ingressStrategy: ''
              tlsSecretName: 'che-tls'
              securityContextFsGroup: ''
              securityContextRunAsUser: ''
              singleHostExposureType: ''
            metrics:
              enable: true
            devWorkspace:
              enable: false
        - apiVersion: org.eclipse.che/v1
          kind: CheClusterBackup
          metadata:
            name: eclipse-che-backup
            namespace: eclipse-che
          spec:
            useInternalBackupServer: false
            backupServerConfigRef: eclipse-che-backup-server-configuration
        - apiVersion: org.eclipse.che/v1
          kind: CheClusterRestore
          metadata:
            name: eclipse-che-restore
            namespace: eclipse-che
          spec:
            backupServerConfigRef: eclipse-che-backup-server-configuration
        - apiVersion: org.eclipse.che/v1
          kind: CheBackupServerConfiguration
          metadata:
            name: eclipse-che-backup-server-configuration
            namespace: eclipse-che
          spec:
            awss3:
              awsAccessKeySecretRef: minio-credentials-secret
              hostname: minio.mydomain.net
              port: 9000
              protocol: http
              repositoryPath: che-backups-bucket
              repositoryPasswordSecretRef: secret-name
      artifacthub.io/license: EPL-2.0
      artifacthub.io/links: |
        - name: repository
          url: https://github.com/eclipse-che/che-operator
        - name: web-site
          url: https://www.eclipse.org/che/
        - name: docs
          url: https://www.eclipse.org/che/docs
        - name: support
          url: https://github.com/eclipse/che
      artifacthub.io/maintainers: |
        - name: Anatolii Bazko
          email: abazko@redhat.com
        - name: Mykola Morhun
          email: mmorhun@redhat.com
        - name: Oleksandr Andriienko
          email: oandriie@redhat.com
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Seamless Upgrades
      artifacthub.io/provider: Eclipse Foundation
    apiVersion: v1
    created: "2021-12-03T11:17:22.491856498Z"
    description: A Helm chart for deploying Eclipse Che on a Kubernetes
    digest: d878115d17844680d8eb1b4ba1760950840dd344e0b6f139e75d78092057eaaf
    name: eclipse-che
    urls:
    - https://eclipse-che.github.io/che-operator/charts/stable/eclipse-che-7.39.2.tgz
    version: 7.39.2
generated: "2021-12-03T11:17:22.490133188Z"
