kind: Job
apiVersion: batch/v1
metadata:
  name: force-pulling-olm-images-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  template:
    metadata:
      name: force-pulling-olm-images-job
    spec:
      volumes:
        - name: util
          emptyDir: {}
      initContainers:

        - name: util
          image: >-
            busybox
          command:
            - /bin/cp
            - '-Rv'
            - /bin/echo
            - /util/echo
          volumeMounts:
            - name: util
              mountPath: /util
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent

      containers:

        - name: pull-bundle-image
          image: 'docker.io/aandrienko/che_operator_bundle:0.0.1'
          command:
            - /util/echo
            - "Pull completed"
          volumeMounts:
            - name: util
              mountPath: /util
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always

        - name: pull-catalog-source-image
          image: 'docker.io/aandrienko/testing_catalog:0.0.1'
          command:
            - echo
            - "Pull completed"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always

      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
