## Append samples you want in your CSV to this file as resources ##
resources:
- org.eclipse.che_v1_checluster.yaml
# Uncomment it to enable sample for CheCluster with version v2alphav1
# - org_v2alpha1_checluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
