#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#
name: Minikube
on: pull_request
jobs:
  minikube-gateway:
    name: Testing latest changes (single-host/gateway)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Start minikube cluster
      id: run-minikube
      uses: che-incubator/setup-minikube-action@next
      with:
        minikube-version: v1.18.1
    - name: Enable local registry
      run: /bin/bash olm/minikube-registry-addon.sh &
    - name: Install yq
      run: sudo pip install yq
    - name: Install chectl
      run: bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/test-operator-singlehost-gateway.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-gateway-artifacts
        path: /tmp/artifacts-che
  minikube-native:
    name: Testing latest changes (single-host/native)
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Download minikube
      run: curl -LO https://storage.googleapis.com/minikube/releases/v1.18.1/minikube-linux-amd64
    - name: Install minikube
      run: sudo install minikube-linux-amd64 /usr/local/bin/minikube
    - name: Start minikube cluster
      run: minikube start --memory=6000 --cpus=2
    - name: Enable ingress addon
      run: minikube addons enable ingress
    - name: Enable local registry
      run: /bin/bash olm/minikube-registry-addon.sh &
    - name: Install yq
      run: sudo pip install yq
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run tests
      run: /bin/bash .github/bin/minikube/test-operator-singlehost-native.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-single-host-native-artifacts
        path: /tmp/artifacts-che
