#
#  Copyright (c) 2012-2020 Red Hat, Inc.
#    This program and the accompanying materials are made
#    available under the terms of the Eclipse Public License 2.0
#    which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#    Red Hat, Inc. - initial API and implementation
#

name: Testing single host nightly deployment
on: pull_request
jobs:
  minikube-shost:
    name: Minikube
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install minikube kubernetes cluster
      run:  /bin/bash .ci/start-minikube.sh
    - name: Install jq
      run: sudo pip install yq
    - name: Install chectl
      run: bash <(curl -sL  https://www.eclipse.org/che/chectl/) --channel=next
    - name: Run che operator single host tests
      run: /bin/bash .ci/cico_minikube_shost.sh
    # Run this step even the previous step fail to upload artifacts to GH
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: minikube-updates-artifacts
        path: /tmp/artifacts-che
